services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vinicius
      POSTGRES_DB: shopper
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shopper"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  # Aplicação Node.js
  app:
    build:
      context: .
    container_name: node_app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: vinicius
      DATABASE_NAME: shopper
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data: